version: "2"

services:

  nginx: #ここを追加する
    image: nginx:1.13
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static #staticも繋ぐ
    depends_on:
      - web

  db-postgres:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  web:
    build: ./web
    volumes:
      - ./src:/code
      - ./static:/static
    expose:
      - "8080" #ポートフォワードじゃなくて普通にport空ける
    mem_limit: 2g
    depends_on:
      - db-postgres
    command: uwsgi --ini /code/bird_pictures/uwsgi.ini #uwsgi起動に変更
    expose:
      - "8080"

  git:
    build: ./web
    command: git clone https://github.com/pjreddie/darknet.git
    depends_on:
      - web

#　開発中定義
#　本番にあげるときはこっちをコメントアウトするよ
#  web:
#    build: ./web
#    volumes:
#      - ./src:/code
#      - ./static:/static
#    depends_on:
#      - db-postgres
#    command: python manage.py runserver 0.0.0.0:8080
#    ports:
#      - "8080:8080"